micronaut:
  application:
    name: registrationService

twilio:
  messaging:
    supported-languages:
      - en

  verify:
    # For a current list of supported languages, please see https://www.twilio.com/docs/verify/supported-languages
    supported-languages:
      - af
      - ar
      - ca
      - zh
      - zh-CN
      - zh-HK
      - hr
      - cs
      - da
      - nl
      - en
      - en-GB
      - et
      - fi
      - fr
      - de
      - el
      - he
      - hi
      - hu
      - id
      - it
      - ja
      - kn
      - ko
      - lt
      - ms
      - mr
      - nb
      - pl
      - pt-BR
      - pt
      - ro
      - ru
      - sk
      - es
      - sv
      - tl
      - te
      - th
      - tr
      - uk
      - vi

  voice:
    supported-languages:
      - am
      - ar
      - bg
      - bn
      - bs
      - cs
      - da
      - de
      - el
      - en-AU
      - en-BD
      - en-CN
      - en-GB
      - en-IN
      - en-NZ
      - en-PK
      - en-SG
      - en-US
      - es
      - es-ES
      - es-MX
      - et
      - fa
      - fi
      - fr
      - fr-CA
      - he
      - hi
      - hr
      - ht
      - hu
      - hy
      - id
      - is
      - it
      - ja
      - kk
      - km
      - ko
      - lo
      - lt
      - lv
      - mr
      - my
      - nl
      - nl-BE
      - no
      - pa
      - pl
      - pt
      - pt-BR
      - ro
      - ru
      - si
      - sk
      - sl
      - so
      - sq
      - sr
      - sv
      - ta
      - te
      - th
      - tr
      - uk
      - ur
      - vi
      - zh
      - zh-HK
      - zh-TW
