micronaut:
  application:
    name: registration-service

  metrics:
    binders:
      netty:
        queues:
          enabled: true

    export:
      datadog:
        enabled: false
        step: 20s
        apiKey:

    tags:
      # Note that an `instance` tag is added at runtime in `Application.java`
      service: registration

  executors:
    scheduled:
      type: scheduled
      core-pool-size: 16

grpc:
  server:
    secure: false
#    ssl:
#      cert-chain: classpath:fullchain.pem
#      private-key: classpath:privkey.pem
