name: Build and push Docker image to GCR

on:
  workflow_call:
    inputs:
      registry_login_server:
        required: true
        type: string
      workload_identity_provider:
        required: true
        type: string
      service_account:
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main project
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v1.0.0
        with:
          workload_identity_provider: ${{ inputs.workload_identity_provider }}
          service_account: ${{ inputs.service_account }}

      - name: Log in to Docker
        run: |-
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
          gcloud auth configure-docker

      - name: Build and push container image
        run: |
          ./mvnw -e -B deploy \
            -Dpackaging=docker \
            -Djib.to.image="${{ inputs.registry_login_server }}/registration-service:${GITHUB_REF_NAME}"
